### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by lstep** [AkihiroSuda/go-netfilter-queue#5]
I am on an Ubuntu 18.04 LTS, using libnetfilter 1.0.2 package.
When trying to compile, I get the following error:
```
error: 'uintptr_t' undeclared (first use in this function); did you mean 'intptr_t'?
```

**Comment by AkihiroSuda** [comment]
Could you try `#include <stdint.h>`?

**Comment by tkerdonc** [comment]
Had a similar issue, adding the suggested include to the shipped netfilter.h indeed fixes the issue.
