### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by zhaoxinxin123** [AkihiroSuda/go-netfilter-queue#7]
zxx@zxx-System : go run *.go

go build github.com/AkihiroSuda/go-netfilter-queue: build constraints exclude all Go files in /home/zxx/Go/work/src/github.com/AkihiroSuda/go-netfilter-queue

**Comment by AkihiroSuda** [comment]
gcc not installed?

**Comment by zhaoxinxin123** [comment]
gcc ha been installed.

**Comment by zhaoxinxin123** [comment]
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by AkihiroSuda** [comment]
use go build, not go run?

**Comment by zhaoxinxin123** [comment]
When I set GOARCH=adm64 

zxx@zxx-System-Product-Name-Invalid-entry-length-16-Fixed-up-to-11:~/Go/work/src/mt6d-master$ go build
# pkg-config --cflags  -- libnetfilter_queue
Package libnetfilter_queue was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnetfilter_queue.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libnetfilter_queue' found
pkg-config: exit status 1
zxx@zxx-System-Product-Name-Invalid-entry-length-16-Fixed-up-to-11:~/Go/work/src/mt6d-master$ go run *.go
# pkg-config --cflags  -- libnetfilter_queue
Package libnetfilter_queue was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnetfilter_queue.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libnetfilter_queue' found
pkg-config: exit status 1

When I set GOARCH =386
zxx@zxx-System-Product-Name-Invalid-entry-length-16-Fixed-up-to-11:~/Go/work/src/mt6d-master$ go build
go build github.com/AkihiroSuda/go-netfilter-queue: build constraints exclude all Go files in /home/zxx/Go/work/src/github.com/AkihiroSuda/go-netfilter-queue
zxx@zxx-System-Product-Name-Invalid-entry-length-16-Fixed-up-to-11:~/Go/work/src/mt6d-master$ go run *.go
go build github.com/AkihiroSuda/go-netfilter-queue: build constraints exclude all Go files in /home/zxx/Go/work/src/github.com/AkihiroSuda/go-netfilter-queue

**Comment by u5surf** [comment]
@zhaoxinxin123 
Did you install `libnetfilter-queue-dev` or `libnetfilter_queue-devel` ?
in my centos7:
```
$ sudo yum install -y libnetfilter_queue-devel
...
$ sudo rpm -ql libnetfilter_queue-devel
/usr/include/libnetfilter_queue
/usr/include/libnetfilter_queue/libnetfilter_queue.h
/usr/include/libnetfilter_queue/libnetfilter_queue_ipv4.h
/usr/include/libnetfilter_queue/libnetfilter_queue_ipv6.h
/usr/include/libnetfilter_queue/libnetfilter_queue_tcp.h
/usr/include/libnetfilter_queue/libnetfilter_queue_udp.h
/usr/include/libnetfilter_queue/linux_nfnetlink_queue.h
/usr/include/libnetfilter_queue/pktbuff.h
/usr/lib64/libnetfilter_queue.so
/usr/lib64/pkgconfig/libnetfilter_queue.pc
$ export PKG_CONFIG_PATH=/usr/lib64/pkgconfig/
$ go get github.com/AkihiroSuda/go-netfilter-queue
$ cd AkihiroSuda/go-netfilter-queue/
$ go build
$ 
```
in ubuntu:
Following .travis.yml, it can be installing `libnetfilter-queue-dev` using `apt install` or `apt-get install`.

**Comment by iwind** [comment]
On CentOS, you should install libnetfilter_queue-devel:
~~~
yum install libnetfilter_queue-devel
~~~

This resolved my issue same with yours.
